export const KEYWORDS = {
  global: [
    "Section 125",
    "cafeteria plan",
    "pre-tax benefits",
    "FICA savings",
    "payroll tax savings",
    "benefits administration",
    "Texas benefits",
    "Conroe TX benefits",
    "Willis TX benefits",
  ],
  home: [
    "Section 125 administrator",
    "pre-tax benefits Texas",
    "FICA payroll tax savings",
    "cafeteria plan administration",
    "small business benefits Texas",
  ],
  servicesEmployers: [
    "Section 125 for employers",
    "pre-tax payroll deductions",
    "employer FICA savings",
    "employee net pay increase",
    "cafeteria plan compliance",
    "nondiscrimination testing",
    "NDT testing",
  ],
  servicesBrokers: [
    "broker partner program",
    "co-broker benefits",
    "Section 125 referral",
    "broker referral benefits Texas",
    "supplemental benefits brokers",
  ],
  platform: [
    "benefits administration software",
    "Section 125 platform",
    "QuickBooks benefits integration",
    "payroll roster sync",
    "benefits e-signature",
    "compliance audit trail",
  ],
  calculator: [
    "Section 125 savings calculator",
    "FICA savings calculator",
    "pre-tax benefits calculator",
    "employer payroll tax calculator",
    "employee net pay calculator",
  ],
  compliance: [
    "Section 125 compliance",
    "nondiscrimination testing",
    "Section 125 plan document",
    "adoption agreement",
    "salary reduction agreement",
    "Section 125 audit",
  ],
  about: [
    "Texas benefits administrator",
    "family-run benefits company",
    "Willis TX benefits",
  ],
  partners: [
    "broker partner program",
    "benefits partner Texas",
    "broker recruitment benefits",
  ],
  contact: [
    "Section 125 quote",
    "benefits administration quote",
    "Texas benefits consultant",
  ],
} as const;
